version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=8000
    restart: unless-stopped
    networks:
      - greenie-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - greenie-network

volumes:
  backend_logs:
  backend_uploads:

networks:
  greenie-network:
    driver: bridge